# Generated by Django 4.1.5 on 2023-01-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.EmailField(max_length=250, verbose_name='Email')),
                ('content', models.TextField(verbose_name='Feedback')),
                ('date', models.DateField(verbose_name='Feedback date')),
            ],
        ),
    ]
