# Generated by Django 4.1.5 on 2023-01-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('anons', models.CharField(max_length=250, verbose_name='Anons')),
                ('content', models.TextField(verbose_name='Content')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date of publication')),
                ('link', models.URLField(default=None, verbose_name='Link to GitHub')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
    ]
