# Generated by Django 4.1.5 on 2023-01-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_articles_options_articles_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateField(verbose_name='Date of publication'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='file',
            field=models.FileField(blank=True, default=None, max_length=250, null=True, upload_to=''),
        ),
    ]
