# Generated by Django 4.1.5 on 2023-01-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_articles_date_alter_articles_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Date of publication'),
        ),
    ]
